global:
  device: cpu
  savedir: output/exp/
  seed: 123
  debug: false

model:
  hidden_dims: 128
  perplexity: 10
  use_mlp: false
  lamda: 0.1
  before: false

train:
  lr: 0.001
  epochs: 500
  eval_epochs: 10
  batch_size: 1024

dataset:
  datadir: data
  dataname: Scene-15
  incomplete_ratio: 0.5
  views: [0, 1]
