global:
  device: 0
  savedir: output/visualize/
  seed: 123
  debug: false
  
model:
  hidden_dims: 128
  perplexity: 10
  use_mlp: false
  lamda: 0.1
  before: false

train:
  lr: 0.001
  epochs: 500
  eval_epochs: 10
  batch_size: 256

dataset:
  datadir: data
  dataname: Digits-10
  incomplete_ratio: 0.5
  views: [0, 1]
